name: Run tests on push

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install 

    - name: Run unit tests
      run: npm run jest-run

    - name: Run E2E tests
      uses: cypress-io/github-action@v5.0.0
      with:
        browser: chrome
        build: npm run build
        start: npm preview

    - name: Check test status
      run: |
        if [ ${{ steps.test.outputs.test_result }} == "failed" ]; then
          echo "Tests failed"
          exit 1
        fi
      env:
        test_result: ${{ toJson(steps.test.outputs.test_result) }}
